# .coveralls.yml example configuration

# same as Ruby lib
repo_token: 5zpxlca00NOqFo97NK8NlgWBF2NlnqL61
# travis-ci or travis-pro
service_name: travis-ci

# for php-coveralls
src_dir: src
coverage_clover: build/logs/clover.xml
#json_path: build/logs/coveralls-upload.json
